const colleges = [
  { name: "Massachusetts Institute of Technology", state: "MA", difficulty_index: 10, gpa_25: 3.92, gpa_50: 3.96, gpa_75: 4.0, majors: ["Engineering", "Computer Science", "Physics", "Mathematics"] },
  { name: "Stanford University", state: "CA", difficulty_index: 10, gpa_25: 3.90, gpa_50: 3.95, gpa_75: 4.0, majors: ["Computer Science", "Engineering", "Business", "Biology"] },
  { name: "Harvard University", state: "MA", difficulty_index: 10, gpa_25: 3.90, gpa_50: 3.95, gpa_75: 4.0, majors: ["Economics", "Government", "Computer Science", "Biology"] },
  { name: "California Institute of Technology", state: "CA", difficulty_index: 10, gpa_25: 3.92, gpa_50: 3.97, gpa_75: 4.0, majors: ["Physics", "Engineering", "Mathematics", "Chemistry"] },
  { name: "Princeton University", state: "NJ", difficulty_index: 10, gpa_25: 3.88, gpa_50: 3.94, gpa_75: 4.0, majors: ["Economics", "Computer Science", "Public Policy", "Engineering"] },
  { name: "Yale University", state: "CT", difficulty_index: 10, gpa_25: 3.88, gpa_50: 3.93, gpa_75: 3.99, majors: ["Economics", "Political Science", "History", "Biology"] },
  { name: "Columbia University", state: "NY", difficulty_index: 10, gpa_25: 3.86, gpa_50: 3.92, gpa_75: 3.98, majors: ["Economics", "Computer Science", "Political Science", "Engineering"] },
  { name: "University of Chicago", state: "IL", difficulty_index: 9, gpa_25: 3.85, gpa_50: 3.92, gpa_75: 3.98, majors: ["Economics", "Mathematics", "Biology", "Political Science"] },
  { name: "University of Pennsylvania", state: "PA", difficulty_index: 10, gpa_25: 3.85, gpa_50: 3.91, gpa_75: 3.97, majors: ["Business", "Economics", "Nursing", "Engineering"] },
  { name: "Duke University", state: "NC", difficulty_index: 9, gpa_25: 3.84, gpa_50: 3.91, gpa_75: 3.97, majors: ["Computer Science", "Economics", "Public Policy", "Biology"] },
  { name: "Johns Hopkins University", state: "MD", difficulty_index: 9, gpa_25: 3.84, gpa_50: 3.90, gpa_75: 3.96, majors: ["Biology", "Neuroscience", "Public Health", "Engineering"] },
  { name: "Northwestern University", state: "IL", difficulty_index: 9, gpa_25: 3.83, gpa_50: 3.90, gpa_75: 3.96, majors: ["Economics", "Journalism", "Engineering", "Theatre"] },
  { name: "Dartmouth College", state: "NH", difficulty_index: 9, gpa_25: 3.82, gpa_50: 3.89, gpa_75: 3.96, majors: ["Economics", "Government", "Computer Science", "Engineering"] },
  { name: "Brown University", state: "RI", difficulty_index: 9, gpa_25: 3.82, gpa_50: 3.89, gpa_75: 3.95, majors: ["Computer Science", "Economics", "Biology", "Engineering"] },
  { name: "Vanderbilt University", state: "TN", difficulty_index: 9, gpa_25: 3.80, gpa_50: 3.88, gpa_75: 3.95, majors: ["Economics", "Medicine", "Education", "Engineering"] },
  { name: "Rice University", state: "TX", difficulty_index: 9, gpa_25: 3.80, gpa_50: 3.88, gpa_75: 3.95, majors: ["Engineering", "Computer Science", "Architecture", "Biology"] },
  { name: "Washington University in St. Louis", state: "MO", difficulty_index: 9, gpa_25: 3.80, gpa_50: 3.88, gpa_75: 3.95, majors: ["Business", "Biology", "Engineering", "Psychology"] },
  { name: "Cornell University", state: "NY", difficulty_index: 9, gpa_25: 3.78, gpa_50: 3.86, gpa_75: 3.94, majors: ["Engineering", "Business", "Biology", "Computer Science"] },
  { name: "University of Notre Dame", state: "IN", difficulty_index: 8, gpa_25: 3.76, gpa_50: 3.85, gpa_75: 3.93, majors: ["Business", "Engineering", "Political Science", "Biology"] },
  { name: "Georgetown University", state: "DC", difficulty_index: 8, gpa_25: 3.76, gpa_50: 3.84, gpa_75: 3.92, majors: ["International Relations", "Government", "Business", "Biology"] },
  { name: "Emory University", state: "GA", difficulty_index: 8, gpa_25: 3.74, gpa_50: 3.83, gpa_75: 3.92, majors: ["Business", "Biology", "Nursing", "Psychology"] },
  { name: "University of California, Los Angeles", state: "CA", difficulty_index: 8, gpa_25: 3.80, gpa_50: 3.90, gpa_75: 3.97, majors: ["Biology", "Psychology", "Economics", "Political Science"] },
  { name: "University of California, Berkeley", state: "CA", difficulty_index: 8, gpa_25: 3.78, gpa_50: 3.89, gpa_75: 3.96, majors: ["Computer Science", "Engineering", "Economics", "Biology"] },
  { name: "University of Southern California", state: "CA", difficulty_index: 8, gpa_25: 3.72, gpa_50: 3.82, gpa_75: 3.92, majors: ["Business", "Film", "Engineering", "Communication"] },
  { name: "Carnegie Mellon University", state: "PA", difficulty_index: 9, gpa_25: 3.78, gpa_50: 3.87, gpa_75: 3.95, majors: ["Computer Science", "Engineering", "Business", "Art"] },
  { name: "University of Virginia", state: "VA", difficulty_index: 7, gpa_25: 3.70, gpa_50: 3.82, gpa_75: 3.92, majors: ["Commerce", "Economics", "Engineering", "Biology"] },
  { name: "Wake Forest University", state: "NC", difficulty_index: 7, gpa_25: 3.65, gpa_50: 3.78, gpa_75: 3.90, majors: ["Business", "Biology", "Communication", "Psychology"] },
  { name: "University of Michigan", state: "MI", difficulty_index: 7, gpa_25: 3.70, gpa_50: 3.82, gpa_75: 3.92, majors: ["Business", "Engineering", "Computer Science", "Economics"] },
  { name: "New York University", state: "NY", difficulty_index: 7, gpa_25: 3.60, gpa_50: 3.75, gpa_75: 3.88, majors: ["Business", "Film", "Economics", "Computer Science"] },
  { name: "Tufts University", state: "MA", difficulty_index: 8, gpa_25: 3.72, gpa_50: 3.83, gpa_75: 3.92, majors: ["International Relations", "Biology", "Computer Science", "Engineering"] },
  { name: "University of North Carolina at Chapel Hill", state: "NC", difficulty_index: 7, gpa_25: 3.65, gpa_50: 3.80, gpa_75: 3.92, majors: ["Business", "Biology", "Media", "Computer Science"] },
  { name: "Boston College", state: "MA", difficulty_index: 7, gpa_25: 3.65, gpa_50: 3.78, gpa_75: 3.90, majors: ["Finance", "Biology", "Economics", "Nursing"] },
  { name: "Boston University", state: "MA", difficulty_index: 7, gpa_25: 3.55, gpa_50: 3.72, gpa_75: 3.86, majors: ["Business", "Engineering", "Biology", "Communication"] },
  { name: "William & Mary", state: "VA", difficulty_index: 7, gpa_25: 3.65, gpa_50: 3.78, gpa_75: 3.90, majors: ["Business", "Government", "Biology", "Computer Science"] },
  { name: "University of Rochester", state: "NY", difficulty_index: 7, gpa_25: 3.55, gpa_50: 3.72, gpa_75: 3.86, majors: ["Engineering", "Music", "Biology", "Economics"] },
  { name: "Brandeis University", state: "MA", difficulty_index: 7, gpa_25: 3.50, gpa_50: 3.70, gpa_75: 3.85, majors: ["Biology", "Economics", "Psychology", "Computer Science"] },
  { name: "Georgia Institute of Technology", state: "GA", difficulty_index: 8, gpa_25: 3.72, gpa_50: 3.84, gpa_75: 3.94, majors: ["Engineering", "Computer Science", "Business", "Biology"] },
  { name: "University of Florida", state: "FL", difficulty_index: 6, gpa_25: 3.60, gpa_50: 3.78, gpa_75: 3.90, majors: ["Business", "Engineering", "Biology", "Psychology"] },
  { name: "University of California, San Diego", state: "CA", difficulty_index: 7, gpa_25: 3.65, gpa_50: 3.80, gpa_75: 3.92, majors: ["Biology", "Computer Science", "Engineering", "Economics"] },
  { name: "University of California, Davis", state: "CA", difficulty_index: 6, gpa_25: 3.55, gpa_50: 3.73, gpa_75: 3.88, majors: ["Biology", "Agricultural Science", "Engineering", "Psychology"] },
  { name: "University of California, Santa Barbara", state: "CA", difficulty_index: 6, gpa_25: 3.55, gpa_50: 3.72, gpa_75: 3.87, majors: ["Economics", "Biology", "Communication", "Psychology"] },
  { name: "University of California, Irvine", state: "CA", difficulty_index: 6, gpa_25: 3.52, gpa_50: 3.70, gpa_75: 3.86, majors: ["Biology", "Computer Science", "Engineering", "Business"] },
  { name: "University of Texas at Austin", state: "TX", difficulty_index: 7, gpa_25: 3.55, gpa_50: 3.72, gpa_75: 3.88, majors: ["Business", "Engineering", "Computer Science", "Communication"] },
  { name: "University of Wisconsin-Madison", state: "WI", difficulty_index: 6, gpa_25: 3.50, gpa_50: 3.70, gpa_75: 3.86, majors: ["Business", "Engineering", "Biology", "Computer Science"] },
  { name: "University of Illinois Urbana-Champaign", state: "IL", difficulty_index: 6, gpa_25: 3.50, gpa_50: 3.70, gpa_75: 3.86, majors: ["Engineering", "Computer Science", "Business", "Biology"] },
  { name: "Lehigh University", state: "PA", difficulty_index: 6, gpa_25: 3.40, gpa_50: 3.62, gpa_75: 3.80, majors: ["Engineering", "Business", "Computer Science", "Biology"] },
  { name: "Northeastern University", state: "MA", difficulty_index: 7, gpa_25: 3.55, gpa_50: 3.73, gpa_75: 3.88, majors: ["Engineering", "Business", "Computer Science", "Health Science"] },
  { name: "Tulane University", state: "LA", difficulty_index: 7, gpa_25: 3.45, gpa_50: 3.65, gpa_75: 3.82, majors: ["Business", "Biology", "Public Health", "Architecture"] },
  { name: "Pepperdine University", state: "CA", difficulty_index: 6, gpa_25: 3.45, gpa_50: 3.65, gpa_75: 3.82, majors: ["Business", "Communication", "Psychology", "Biology"] },
  { name: "University of Georgia", state: "GA", difficulty_index: 6, gpa_25: 3.50, gpa_50: 3.70, gpa_75: 3.86, majors: ["Business", "Biology", "Education", "Journalism"] },
  { name: "Ohio State University", state: "OH", difficulty_index: 5, gpa_25: 3.45, gpa_50: 3.65, gpa_75: 3.82, majors: ["Business", "Engineering", "Biology", "Psychology"] },
  { name: "Purdue University", state: "IN", difficulty_index: 6, gpa_25: 3.45, gpa_50: 3.65, gpa_75: 3.82, majors: ["Engineering", "Computer Science", "Business", "Agriculture"] },
  { name: "University of Washington", state: "WA", difficulty_index: 6, gpa_25: 3.55, gpa_50: 3.72, gpa_75: 3.88, majors: ["Computer Science", "Engineering", "Biology", "Business"] },
  { name: "Villanova University", state: "PA", difficulty_index: 6, gpa_25: 3.50, gpa_50: 3.70, gpa_75: 3.86, majors: ["Business", "Nursing", "Engineering", "Biology"] },
  { name: "University of Maryland", state: "MD", difficulty_index: 6, gpa_25: 3.50, gpa_50: 3.70, gpa_75: 3.86, majors: ["Computer Science", "Engineering", "Business", "Biology"] },
  { name: "Case Western Reserve University", state: "OH", difficulty_index: 7, gpa_25: 3.50, gpa_50: 3.70, gpa_75: 3.86, majors: ["Engineering", "Biology", "Nursing", "Computer Science"] },
  { name: "Rensselaer Polytechnic Institute", state: "NY", difficulty_index: 6, gpa_25: 3.45, gpa_50: 3.65, gpa_75: 3.82, majors: ["Engineering", "Computer Science", "Architecture", "Business"] },
  { name: "University of Minnesota", state: "MN", difficulty_index: 5, gpa_25: 3.40, gpa_50: 3.62, gpa_75: 3.80, majors: ["Business", "Engineering", "Biology", "Psychology"] },
  { name: "University of Connecticut", state: "CT", difficulty_index: 5, gpa_25: 3.40, gpa_50: 3.62, gpa_75: 3.80, majors: ["Business", "Engineering", "Biology", "Nursing"] },
  { name: "Santa Clara University", state: "CA", difficulty_index: 6, gpa_25: 3.50, gpa_50: 3.70, gpa_75: 3.86, majors: ["Business", "Engineering", "Computer Science", "Communication"] },
  { name: "Stevens Institute of Technology", state: "NJ", difficulty_index: 6, gpa_25: 3.40, gpa_50: 3.62, gpa_75: 3.80, majors: ["Engineering", "Computer Science", "Business", "Mathematics"] },
  { name: "Syracuse University", state: "NY", difficulty_index: 5, gpa_25: 3.30, gpa_50: 3.55, gpa_75: 3.76, majors: ["Communication", "Business", "Engineering", "Architecture"] },
  { name: "University of Pittsburgh", state: "PA", difficulty_index: 5, gpa_25: 3.40, gpa_50: 3.62, gpa_75: 3.80, majors: ["Business", "Engineering", "Biology", "Nursing"] },
  { name: "George Washington University", state: "DC", difficulty_index: 6, gpa_25: 3.40, gpa_50: 3.62, gpa_75: 3.80, majors: ["International Affairs", "Political Science", "Business", "Engineering"] },
  { name: "Fordham University", state: "NY", difficulty_index: 5, gpa_25: 3.35, gpa_50: 3.58, gpa_75: 3.78, majors: ["Business", "Communication", "Biology", "Psychology"] },
  { name: "Southern Methodist University", state: "TX", difficulty_index: 6, gpa_25: 3.40, gpa_50: 3.62, gpa_75: 3.80, majors: ["Business", "Engineering", "Economics", "Communication"] },
  { name: "University of Miami", state: "FL", difficulty_index: 6, gpa_25: 3.40, gpa_50: 3.62, gpa_75: 3.80, majors: ["Business", "Marine Biology", "Engineering", "Music"] },
  { name: "Penn State University", state: "PA", difficulty_index: 5, gpa_25: 3.35, gpa_50: 3.58, gpa_75: 3.78, majors: ["Business", "Engineering", "Biology", "Communication"] },
  { name: "Rutgers University", state: "NJ", difficulty_index: 5, gpa_25: 3.30, gpa_50: 3.55, gpa_75: 3.76, majors: ["Business", "Engineering", "Biology", "Computer Science"] },
  { name: "University of Iowa", state: "IA", difficulty_index: 5, gpa_25: 3.25, gpa_50: 3.50, gpa_75: 3.74, majors: ["Business", "Engineering", "Biology", "Writing"] },
  { name: "University of Denver", state: "CO", difficulty_index: 5, gpa_25: 3.35, gpa_50: 3.58, gpa_75: 3.78, majors: ["Business", "International Studies", "Engineering", "Psychology"] },
  { name: "Indiana University Bloomington", state: "IN", difficulty_index: 5, gpa_25: 3.25, gpa_50: 3.50, gpa_75: 3.74, majors: ["Business", "Music", "Education", "Computer Science"] },
  { name: "Michigan State University", state: "MI", difficulty_index: 5, gpa_25: 3.25, gpa_50: 3.50, gpa_75: 3.74, majors: ["Business", "Engineering", "Education", "Agriculture"] },
  { name: "University of Colorado Boulder", state: "CO", difficulty_index: 5, gpa_25: 3.25, gpa_50: 3.50, gpa_75: 3.74, majors: ["Engineering", "Business", "Environmental Science", "Psychology"] },
  { name: "Clemson University", state: "SC", difficulty_index: 5, gpa_25: 3.35, gpa_50: 3.58, gpa_75: 3.78, majors: ["Engineering", "Business", "Agriculture", "Architecture"] },
  { name: "Texas A&M University", state: "TX", difficulty_index: 5, gpa_25: 3.35, gpa_50: 3.60, gpa_75: 3.80, majors: ["Engineering", "Business", "Agriculture", "Biology"] },
  { name: "Virginia Tech", state: "VA", difficulty_index: 5, gpa_25: 3.40, gpa_50: 3.62, gpa_75: 3.80, majors: ["Engineering", "Computer Science", "Business", "Architecture"] },
  { name: "University of California, Santa Cruz", state: "CA", difficulty_index: 5, gpa_25: 3.35, gpa_50: 3.58, gpa_75: 3.78, majors: ["Computer Science", "Marine Biology", "Psychology", "Film"] },
  { name: "University of California, Riverside", state: "CA", difficulty_index: 5, gpa_25: 3.25, gpa_50: 3.50, gpa_75: 3.74, majors: ["Business", "Engineering", "Biology", "Psychology"] },
  { name: "American University", state: "DC", difficulty_index: 5, gpa_25: 3.30, gpa_50: 3.55, gpa_75: 3.76, majors: ["International Relations", "Political Science", "Business", "Communication"] },
  { name: "Loyola Marymount University", state: "CA", difficulty_index: 5, gpa_25: 3.40, gpa_50: 3.62, gpa_75: 3.80, majors: ["Business", "Film", "Engineering", "Communication"] },
  { name: "University of San Diego", state: "CA", difficulty_index: 5, gpa_25: 3.35, gpa_50: 3.58, gpa_75: 3.78, majors: ["Business", "Engineering", "Biology", "Communication"] },
  { name: "University of San Francisco", state: "CA", difficulty_index: 5, gpa_25: 3.25, gpa_50: 3.50, gpa_75: 3.74, majors: ["Business", "Nursing", "Psychology", "Biology"] },
  { name: "Drexel University", state: "PA", difficulty_index: 5, gpa_25: 3.20, gpa_50: 3.48, gpa_75: 3.72, majors: ["Engineering", "Business", "Nursing", "Computer Science"] },
  { name: "Marquette University", state: "WI", difficulty_index: 5, gpa_25: 3.30, gpa_50: 3.55, gpa_75: 3.76, majors: ["Business", "Nursing", "Engineering", "Communication"] },
  { name: "Baylor University", state: "TX", difficulty_index: 5, gpa_25: 3.30, gpa_50: 3.55, gpa_75: 3.76, majors: ["Business", "Biology", "Nursing", "Engineering"] },
  { name: "University of Delaware", state: "DE", difficulty_index: 5, gpa_25: 3.25, gpa_50: 3.50, gpa_75: 3.74, majors: ["Business", "Engineering", "Education", "Biology"] },
  { name: "University of South Carolina", state: "SC", difficulty_index: 4, gpa_25: 3.20, gpa_50: 3.48, gpa_75: 3.72, majors: ["Business", "International Business", "Engineering", "Biology"] },
  { name: "University of Tennessee", state: "TN", difficulty_index: 4, gpa_25: 3.20, gpa_50: 3.48, gpa_75: 3.72, majors: ["Business", "Engineering", "Agriculture", "Communication"] },
  { name: "Auburn University", state: "AL", difficulty_index: 4, gpa_25: 3.20, gpa_50: 3.48, gpa_75: 3.72, majors: ["Engineering", "Business", "Architecture", "Agriculture"] },
  { name: "University of Alabama", state: "AL", difficulty_index: 4, gpa_25: 3.10, gpa_50: 3.40, gpa_75: 3.68, majors: ["Business", "Engineering", "Communication", "Nursing"] },
  { name: "Iowa State University", state: "IA", difficulty_index: 4, gpa_25: 3.10, gpa_50: 3.40, gpa_75: 3.68, majors: ["Engineering", "Agriculture", "Business", "Computer Science"] },
  { name: "University of Kansas", state: "KS", difficulty_index: 4, gpa_25: 3.05, gpa_50: 3.35, gpa_75: 3.65, majors: ["Business", "Engineering", "Journalism", "Education"] },
  { name: "University of Oregon", state: "OR", difficulty_index: 4, gpa_25: 3.15, gpa_50: 3.45, gpa_75: 3.70, majors: ["Business", "Journalism", "Architecture", "Psychology"] },
  { name: "University of Kentucky", state: "KY", difficulty_index: 4, gpa_25: 3.10, gpa_50: 3.40, gpa_75: 3.68, majors: ["Business", "Engineering", "Agriculture", "Pharmacy"] },
  { name: "Colorado State University", state: "CO", difficulty_index: 4, gpa_25: 3.10, gpa_50: 3.40, gpa_75: 3.68, majors: ["Veterinary Science", "Engineering", "Business", "Agriculture"] },
  { name: "University of Arizona", state: "AZ", difficulty_index: 4, gpa_25: 3.05, gpa_50: 3.35, gpa_75: 3.65, majors: ["Business", "Engineering", "Optical Sciences", "Astronomy"] },
  { name: "Arizona State University", state: "AZ", difficulty_index: 4, gpa_25: 3.10, gpa_50: 3.40, gpa_75: 3.68, majors: ["Business", "Engineering", "Journalism", "Computer Science"] },
  { name: "University of Nebraska-Lincoln", state: "NE", difficulty_index: 4, gpa_25: 3.00, gpa_50: 3.30, gpa_75: 3.62, majors: ["Business", "Engineering", "Agriculture", "Education"] },
  { name: "Oregon State University", state: "OR", difficulty_index: 4, gpa_25: 3.05, gpa_50: 3.35, gpa_75: 3.65, majors: ["Engineering", "Forestry", "Business", "Agriculture"] },
  { name: "University of Missouri", state: "MO", difficulty_index: 4, gpa_25: 3.05, gpa_50: 3.35, gpa_75: 3.65, majors: ["Journalism", "Business", "Engineering", "Agriculture"] },
  { name: "University of Oklahoma", state: "OK", difficulty_index: 4, gpa_25: 3.00, gpa_50: 3.30, gpa_75: 3.62, majors: ["Business", "Engineering", "Meteorology", "Education"] },
  { name: "Washington State University", state: "WA", difficulty_index: 4, gpa_25: 3.00, gpa_50: 3.30, gpa_75: 3.62, majors: ["Business", "Engineering", "Agriculture", "Veterinary Science"] },
  { name: "University of Mississippi", state: "MS", difficulty_index: 3, gpa_25: 2.90, gpa_50: 3.20, gpa_75: 3.55, majors: ["Business", "Pharmacy", "Education", "Journalism"] },
  { name: "University of Arkansas", state: "AR", difficulty_index: 3, gpa_25: 2.95, gpa_50: 3.25, gpa_75: 3.58, majors: ["Business", "Engineering", "Agriculture", "Education"] },
  { name: "Kansas State University", state: "KS", difficulty_index: 3, gpa_25: 2.90, gpa_50: 3.20, gpa_75: 3.55, majors: ["Engineering", "Agriculture", "Business", "Architecture"] },
  { name: "Mississippi State University", state: "MS", difficulty_index: 3, gpa_25: 2.85, gpa_50: 3.15, gpa_75: 3.50, majors: ["Engineering", "Agriculture", "Business", "Architecture"] },
  { name: "University of Nevada, Las Vegas", state: "NV", difficulty_index: 3, gpa_25: 2.80, gpa_50: 3.10, gpa_75: 3.48, majors: ["Hospitality", "Business", "Engineering", "Education"] },
  { name: "Florida State University", state: "FL", difficulty_index: 5, gpa_25: 3.35, gpa_50: 3.60, gpa_75: 3.80, majors: ["Business", "Film", "Criminology", "Biology"] },
  { name: "University of South Florida", state: "FL", difficulty_index: 4, gpa_25: 3.10, gpa_50: 3.40, gpa_75: 3.68, majors: ["Business", "Engineering", "Medicine", "Education"] },
  { name: "University of Central Florida", state: "FL", difficulty_index: 4, gpa_25: 3.05, gpa_50: 3.35, gpa_75: 3.65, majors: ["Engineering", "Business", "Hospitality", "Computer Science"] },
  { name: "North Carolina State University", state: "NC", difficulty_index: 5, gpa_25: 3.40, gpa_50: 3.62, gpa_75: 3.80, majors: ["Engineering", "Computer Science", "Agriculture", "Business"] },
  { name: "University of Massachusetts Amherst", state: "MA", difficulty_index: 5, gpa_25: 3.30, gpa_50: 3.55, gpa_75: 3.76, majors: ["Computer Science", "Engineering", "Business", "Biology"] },
  { name: "Temple University", state: "PA", difficulty_index: 4, gpa_25: 3.05, gpa_50: 3.35, gpa_75: 3.65, majors: ["Business", "Communication", "Art", "Engineering"] },
  { name: "University of Vermont", state: "VT", difficulty_index: 5, gpa_25: 3.25, gpa_50: 3.50, gpa_75: 3.74, majors: ["Environmental Science", "Business", "Biology", "Education"] },
  { name: "University of New Hampshire", state: "NH", difficulty_index: 4, gpa_25: 3.10, gpa_50: 3.40, gpa_75: 3.68, majors: ["Business", "Engineering", "Marine Science", "Education"] },
  { name: "University of Rhode Island", state: "RI", difficulty_index: 4, gpa_25: 3.00, gpa_50: 3.30, gpa_75: 3.62, majors: ["Pharmacy", "Marine Science", "Engineering", "Business"] },
  { name: "University of Maine", state: "ME", difficulty_index: 3, gpa_25: 2.90, gpa_50: 3.20, gpa_75: 3.55, majors: ["Engineering", "Marine Science", "Education", "Business"] },
  { name: "University of Hawaii at Manoa", state: "HI", difficulty_index: 4, gpa_25: 3.00, gpa_50: 3.30, gpa_75: 3.62, majors: ["Marine Biology", "Asian Studies", "Engineering", "Business"] },
  { name: "University of Wyoming", state: "WY", difficulty_index: 3, gpa_25: 2.80, gpa_50: 3.10, gpa_75: 3.48, majors: ["Engineering", "Agriculture", "Business", "Education"] },
  { name: "University of Idaho", state: "ID", difficulty_index: 3, gpa_25: 2.80, gpa_50: 3.10, gpa_75: 3.48, majors: ["Engineering", "Agriculture", "Business", "Education"] },
  { name: "University of Montana", state: "MT", difficulty_index: 3, gpa_25: 2.75, gpa_50: 3.05, gpa_75: 3.45, majors: ["Forestry", "Wildlife Biology", "Journalism", "Business"] },
  { name: "Montana State University", state: "MT", difficulty_index: 3, gpa_25: 2.80, gpa_50: 3.10, gpa_75: 3.48, majors: ["Engineering", "Agriculture", "Architecture", "Film"] },
  { name: "Boise State University", state: "ID", difficulty_index: 3, gpa_25: 2.75, gpa_50: 3.05, gpa_75: 3.45, majors: ["Engineering", "Business", "Computer Science", "Education"] },
  { name: "University of North Dakota", state: "ND", difficulty_index: 3, gpa_25: 2.70, gpa_50: 3.00, gpa_75: 3.40, majors: ["Aviation", "Engineering", "Medicine", "Business"] },
  { name: "University of South Dakota", state: "SD", difficulty_index: 3, gpa_25: 2.70, gpa_50: 3.00, gpa_75: 3.40, majors: ["Business", "Health Science", "Education", "Music"] },
  { name: "South Dakota State University", state: "SD", difficulty_index: 3, gpa_25: 2.70, gpa_50: 3.00, gpa_75: 3.40, majors: ["Engineering", "Agriculture", "Nursing", "Pharmacy"] },
  { name: "North Dakota State University", state: "ND", difficulty_index: 3, gpa_25: 2.70, gpa_50: 3.00, gpa_75: 3.40, majors: ["Engineering", "Agriculture", "Architecture", "Pharmacy"] },
  { name: "University of Alaska Fairbanks", state: "AK", difficulty_index: 2, gpa_25: 2.50, gpa_50: 2.85, gpa_75: 3.25, majors: ["Engineering", "Marine Science", "Biology", "Geoscience"] },
  { name: "Creighton University", state: "NE", difficulty_index: 5, gpa_25: 3.30, gpa_50: 3.55, gpa_75: 3.76, majors: ["Business", "Health Science", "Nursing", "Biology"] },
  { name: "Gonzaga University", state: "WA", difficulty_index: 5, gpa_25: 3.35, gpa_50: 3.58, gpa_75: 3.78, majors: ["Business", "Engineering", "Biology", "Education"] },
  { name: "Loyola University Chicago", state: "IL", difficulty_index: 5, gpa_25: 3.25, gpa_50: 3.50, gpa_75: 3.74, majors: ["Business", "Nursing", "Biology", "Psychology"] },
  { name: "University of Dayton", state: "OH", difficulty_index: 4, gpa_25: 3.15, gpa_50: 3.45, gpa_75: 3.70, majors: ["Engineering", "Business", "Education", "Biology"] },
  { name: "Seton Hall University", state: "NJ", difficulty_index: 4, gpa_25: 3.05, gpa_50: 3.35, gpa_75: 3.65, majors: ["Business", "Nursing", "Communication", "Education"] },
  { name: "DePaul University", state: "IL", difficulty_index: 4, gpa_25: 3.05, gpa_50: 3.35, gpa_75: 3.65, majors: ["Business", "Communication", "Computer Science", "Psychology"] },
  { name: "University of the Pacific", state: "CA", difficulty_index: 5, gpa_25: 3.20, gpa_50: 3.48, gpa_75: 3.72, majors: ["Engineering", "Pharmacy", "Music", "Business"] },
  { name: "Chapman University", state: "CA", difficulty_index: 5, gpa_25: 3.30, gpa_50: 3.55, gpa_75: 3.76, majors: ["Film", "Business", "Communication", "Biology"] },
  { name: "Elon University", state: "NC", difficulty_index: 5, gpa_25: 3.30, gpa_50: 3.55, gpa_75: 3.76, majors: ["Business", "Communication", "Education", "Biology"] },
  { name: "Howard University", state: "DC", difficulty_index: 6, gpa_25: 3.20, gpa_50: 3.48, gpa_75: 3.72, majors: ["Business", "Engineering", "Communication", "Biology"] },
  { name: "Spelman College", state: "GA", difficulty_index: 6, gpa_25: 3.30, gpa_50: 3.55, gpa_75: 3.76, majors: ["Biology", "Psychology", "Political Science", "Computer Science"] },
  { name: "Morehouse College", state: "GA", difficulty_index: 5, gpa_25: 3.10, gpa_50: 3.40, gpa_75: 3.68, majors: ["Business", "Biology", "Computer Science", "Political Science"] },
  { name: "Harvey Mudd College", state: "CA", difficulty_index: 10, gpa_25: 3.88, gpa_50: 3.94, gpa_75: 4.0, majors: ["Engineering", "Computer Science", "Physics", "Mathematics"] },
  { name: "Pomona College", state: "CA", difficulty_index: 9, gpa_25: 3.82, gpa_50: 3.90, gpa_75: 3.97, majors: ["Economics", "Computer Science", "Biology", "Mathematics"] },
  { name: "Claremont McKenna College", state: "CA", difficulty_index: 8, gpa_25: 3.75, gpa_50: 3.85, gpa_75: 3.94, majors: ["Economics", "Government", "International Relations", "Philosophy"] },
  { name: "Swarthmore College", state: "PA", difficulty_index: 9, gpa_25: 3.82, gpa_50: 3.90, gpa_75: 3.97, majors: ["Engineering", "Economics", "Biology", "Computer Science"] },
  { name: "Williams College", state: "MA", difficulty_index: 9, gpa_25: 3.84, gpa_50: 3.91, gpa_75: 3.97, majors: ["Economics", "Mathematics", "Biology", "Psychology"] },
  { name: "Amherst College", state: "MA", difficulty_index: 9, gpa_25: 3.82, gpa_50: 3.90, gpa_75: 3.97, majors: ["Economics", "Mathematics", "Biology", "Political Science"] },
  { name: "Bowdoin College", state: "ME", difficulty_index: 8, gpa_25: 3.76, gpa_50: 3.86, gpa_75: 3.94, majors: ["Government", "Economics", "Biology", "Mathematics"] },
  { name: "Middlebury College", state: "VT", difficulty_index: 8, gpa_25: 3.72, gpa_50: 3.83, gpa_75: 3.92, majors: ["Environmental Studies", "Economics", "International Studies", "Biology"] },
  { name: "Colby College", state: "ME", difficulty_index: 7, gpa_25: 3.60, gpa_50: 3.75, gpa_75: 3.88, majors: ["Economics", "Biology", "Government", "Computer Science"] },
  { name: "Bates College", state: "ME", difficulty_index: 7, gpa_25: 3.55, gpa_50: 3.72, gpa_75: 3.86, majors: ["Economics", "Psychology", "Biology", "Politics"] },
  { name: "Colgate University", state: "NY", difficulty_index: 7, gpa_25: 3.55, gpa_50: 3.72, gpa_75: 3.86, majors: ["Economics", "Political Science", "Biology", "English"] },
  { name: "Hamilton College", state: "NY", difficulty_index: 7, gpa_25: 3.55, gpa_50: 3.72, gpa_75: 3.86, majors: ["Economics", "Government", "Mathematics", "Psychology"] },
  { name: "Grinnell College", state: "IA", difficulty_index: 7, gpa_25: 3.55, gpa_50: 3.72, gpa_75: 3.86, majors: ["Biology", "Economics", "Computer Science", "Political Science"] },
  { name: "Wellesley College", state: "MA", difficulty_index: 8, gpa_25: 3.72, gpa_50: 3.83, gpa_75: 3.92, majors: ["Economics", "Computer Science", "Political Science", "Biology"] },
  { name: "Smith College", state: "MA", difficulty_index: 7, gpa_25: 3.55, gpa_50: 3.72, gpa_75: 3.86, majors: ["Government", "Economics", "Engineering", "Biology"] },
  { name: "Vassar College", state: "NY", difficulty_index: 7, gpa_25: 3.55, gpa_50: 3.72, gpa_75: 3.86, majors: ["Political Science", "Economics", "Psychology", "English"] },
  { name: "Wesleyan University", state: "CT", difficulty_index: 8, gpa_25: 3.65, gpa_50: 3.78, gpa_75: 3.90, majors: ["Film", "Economics", "Government", "Psychology"] },
  { name: "Oberlin College", state: "OH", difficulty_index: 6, gpa_25: 3.40, gpa_50: 3.62, gpa_75: 3.80, majors: ["Music", "Biology", "English", "Politics"] },
  { name: "Carleton College", state: "MN", difficulty_index: 8, gpa_25: 3.72, gpa_50: 3.83, gpa_75: 3.92, majors: ["Computer Science", "Economics", "Biology", "Mathematics"] },
  { name: "Macalester College", state: "MN", difficulty_index: 6, gpa_25: 3.45, gpa_50: 3.65, gpa_75: 3.82, majors: ["Economics", "International Studies", "Biology", "Political Science"] },
  { name: "Colorado College", state: "CO", difficulty_index: 6, gpa_25: 3.45, gpa_50: 3.65, gpa_75: 3.82, majors: ["Economics", "Biology", "Sociology", "Environmental Science"] },
  { name: "Reed College", state: "OR", difficulty_index: 6, gpa_25: 3.45, gpa_50: 3.65, gpa_75: 3.82, majors: ["Biology", "English", "Psychology", "Physics"] },
  { name: "Whitman College", state: "WA", difficulty_index: 5, gpa_25: 3.30, gpa_50: 3.55, gpa_75: 3.76, majors: ["Biology", "Economics", "Psychology", "Politics"] },
  { name: "Lewis & Clark College", state: "OR", difficulty_index: 5, gpa_25: 3.25, gpa_50: 3.50, gpa_75: 3.74, majors: ["International Affairs", "Biology", "Environmental Studies", "Psychology"] },
  { name: "Occidental College", state: "CA", difficulty_index: 6, gpa_25: 3.40, gpa_50: 3.62, gpa_75: 3.80, majors: ["Economics", "Diplomacy", "Biology", "Sociology"] },
  { name: "Scripps College", state: "CA", difficulty_index: 7, gpa_25: 3.55, gpa_50: 3.72, gpa_75: 3.86, majors: ["Biology", "Economics", "Media Studies", "Psychology"] },
  { name: "University of Tulsa", state: "OK", difficulty_index: 4, gpa_25: 3.10, gpa_50: 3.40, gpa_75: 3.68, majors: ["Engineering", "Business", "Computer Science", "Petroleum Engineering"] },
  { name: "Stony Brook University", state: "NY", difficulty_index: 5, gpa_25: 3.30, gpa_50: 3.55, gpa_75: 3.76, majors: ["Engineering", "Computer Science", "Biology", "Business"] },
  { name: "University at Buffalo", state: "NY", difficulty_index: 4, gpa_25: 3.10, gpa_50: 3.40, gpa_75: 3.68, majors: ["Engineering", "Business", "Pharmacy", "Architecture"] },
  { name: "Binghamton University", state: "NY", difficulty_index: 5, gpa_25: 3.35, gpa_50: 3.58, gpa_75: 3.78, majors: ["Engineering", "Business", "Computer Science", "Biology"] },
  { name: "University of California, Merced", state: "CA", difficulty_index: 4, gpa_25: 3.00, gpa_50: 3.30, gpa_75: 3.62, majors: ["Engineering", "Biology", "Psychology", "Computer Science"] },
  { name: "San Diego State University", state: "CA", difficulty_index: 5, gpa_25: 3.30, gpa_50: 3.55, gpa_75: 3.76, majors: ["Business", "Engineering", "Criminal Justice", "Psychology"] },
  { name: "University of Houston", state: "TX", difficulty_index: 4, gpa_25: 3.05, gpa_50: 3.35, gpa_75: 3.65, majors: ["Engineering", "Business", "Hospitality", "Computer Science"] },
  { name: "Portland State University", state: "OR", difficulty_index: 3, gpa_25: 2.80, gpa_50: 3.10, gpa_75: 3.48, majors: ["Business", "Engineering", "Social Work", "Urban Studies"] },
  { name: "George Mason University", state: "VA", difficulty_index: 4, gpa_25: 3.10, gpa_50: 3.40, gpa_75: 3.68, majors: ["Engineering", "Business", "Computer Science", "Public Policy"] },
  { name: "James Madison University", state: "VA", difficulty_index: 5, gpa_25: 3.30, gpa_50: 3.55, gpa_75: 3.76, majors: ["Business", "Health Science", "Communication", "Education"] },
  { name: "Old Dominion University", state: "VA", difficulty_index: 3, gpa_25: 2.80, gpa_50: 3.10, gpa_75: 3.48, majors: ["Engineering", "Business", "Maritime", "Education"] },
  { name: "West Virginia University", state: "WV", difficulty_index: 3, gpa_25: 2.80, gpa_50: 3.10, gpa_75: 3.48, majors: ["Engineering", "Business", "Forensic Science", "Agriculture"] },
  { name: "University of New Mexico", state: "NM", difficulty_index: 3, gpa_25: 2.75, gpa_50: 3.05, gpa_75: 3.45, majors: ["Engineering", "Business", "Education", "Fine Arts"] },
  { name: "New Mexico State University", state: "NM", difficulty_index: 3, gpa_25: 2.70, gpa_50: 3.00, gpa_75: 3.40, majors: ["Agriculture", "Engineering", "Business", "Education"] },
  { name: "University of Nevada, Reno", state: "NV", difficulty_index: 3, gpa_25: 2.85, gpa_50: 3.15, gpa_75: 3.50, majors: ["Business", "Engineering", "Mining", "Agriculture"] },
  { name: "Utah State University", state: "UT", difficulty_index: 3, gpa_25: 2.80, gpa_50: 3.10, gpa_75: 3.48, majors: ["Engineering", "Agriculture", "Business", "Education"] },
  { name: "University of Utah", state: "UT", difficulty_index: 4, gpa_25: 3.10, gpa_50: 3.40, gpa_75: 3.68, majors: ["Business", "Engineering", "Computer Science", "Health"] },
  { name: "Brigham Young University", state: "UT", difficulty_index: 5, gpa_25: 3.40, gpa_50: 3.62, gpa_75: 3.80, majors: ["Business", "Engineering", "Education", "Computer Science"] },
  { name: "Duquesne University", state: "PA", difficulty_index: 4, gpa_25: 3.10, gpa_50: 3.40, gpa_75: 3.68, majors: ["Business", "Pharmacy", "Nursing", "Music"] },
  { name: "Xavier University", state: "OH", difficulty_index: 4, gpa_25: 3.10, gpa_50: 3.40, gpa_75: 3.68, majors: ["Business", "Nursing", "Biology", "Education"] },
  { name: "Butler University", state: "IN", difficulty_index: 5, gpa_25: 3.25, gpa_50: 3.50, gpa_75: 3.74, majors: ["Business", "Pharmacy", "Communication", "Education"] },
  { name: "Providence College", state: "RI", difficulty_index: 5, gpa_25: 3.25, gpa_50: 3.50, gpa_75: 3.74, majors: ["Business", "Biology", "Education", "Health Policy"] },
  { name: "College of the Holy Cross", state: "MA", difficulty_index: 6, gpa_25: 3.40, gpa_50: 3.62, gpa_75: 3.80, majors: ["Economics", "Political Science", "Biology", "Psychology"] },
  { name: "Bucknell University", state: "PA", difficulty_index: 6, gpa_25: 3.40, gpa_50: 3.62, gpa_75: 3.80, majors: ["Engineering", "Business", "Biology", "Economics"] },
  { name: "Lafayette College", state: "PA", difficulty_index: 6, gpa_25: 3.35, gpa_50: 3.58, gpa_75: 3.78, majors: ["Engineering", "Economics", "Government", "Biology"] },
  { name: "Dickinson College", state: "PA", difficulty_index: 5, gpa_25: 3.20, gpa_50: 3.48, gpa_75: 3.72, majors: ["International Studies", "Political Science", "Biology", "Economics"] },
  { name: "Gettysburg College", state: "PA", difficulty_index: 5, gpa_25: 3.20, gpa_50: 3.48, gpa_75: 3.72, majors: ["Business", "Political Science", "Biology", "Psychology"] },
  { name: "Muhlenberg College", state: "PA", difficulty_index: 5, gpa_25: 3.20, gpa_50: 3.48, gpa_75: 3.72, majors: ["Business", "Biology", "Theatre", "Psychology"] },
  { name: "Skidmore College", state: "NY", difficulty_index: 5, gpa_25: 3.20, gpa_50: 3.48, gpa_75: 3.72, majors: ["Business", "English", "Art", "Psychology"] },
  { name: "Union College", state: "NY", difficulty_index: 6, gpa_25: 3.30, gpa_50: 3.55, gpa_75: 3.76, majors: ["Engineering", "Economics", "Biology", "Political Science"] },
  { name: "Trinity College", state: "CT", difficulty_index: 5, gpa_25: 3.15, gpa_50: 3.45, gpa_75: 3.70, majors: ["Economics", "Political Science", "Neuroscience", "Engineering"] },
  { name: "Connecticut College", state: "CT", difficulty_index: 5, gpa_25: 3.20, gpa_50: 3.48, gpa_75: 3.72, majors: ["Economics", "Government", "Biology", "Psychology"] },
  { name: "Davidson College", state: "NC", difficulty_index: 7, gpa_25: 3.55, gpa_50: 3.72, gpa_75: 3.86, majors: ["Biology", "Economics", "Political Science", "English"] },
  { name: "Furman University", state: "SC", difficulty_index: 5, gpa_25: 3.25, gpa_50: 3.50, gpa_75: 3.74, majors: ["Biology", "Business", "Political Science", "Health Science"] },
  { name: "Rhodes College", state: "TN", difficulty_index: 5, gpa_25: 3.25, gpa_50: 3.50, gpa_75: 3.74, majors: ["Biology", "Business", "English", "International Studies"] },
  { name: "Sewanee: University of the South", state: "TN", difficulty_index: 5, gpa_25: 3.15, gpa_50: 3.45, gpa_75: 3.70, majors: ["English", "Economics", "Biology", "Environmental Studies"] },
  { name: "Centre College", state: "KY", difficulty_index: 5, gpa_25: 3.20, gpa_50: 3.48, gpa_75: 3.72, majors: ["Economics", "Biology", "Government", "History"] },
  { name: "Kenyon College", state: "OH", difficulty_index: 6, gpa_25: 3.35, gpa_50: 3.58, gpa_75: 3.78, majors: ["English", "Economics", "Biology", "Political Science"] },
  { name: "Denison University", state: "OH", difficulty_index: 5, gpa_25: 3.20, gpa_50: 3.48, gpa_75: 3.72, majors: ["Communication", "Economics", "Biology", "Psychology"] },
  { name: "College of Wooster", state: "OH", difficulty_index: 4, gpa_25: 3.10, gpa_50: 3.40, gpa_75: 3.68, majors: ["Biology", "Business Economics", "History", "Political Science"] },
  { name: "Ohio Wesleyan University", state: "OH", difficulty_index: 4, gpa_25: 3.00, gpa_50: 3.30, gpa_75: 3.62, majors: ["Biology", "Business", "Zoology", "Politics"] },
  { name: "Wabash College", state: "IN", difficulty_index: 4, gpa_25: 3.00, gpa_50: 3.30, gpa_75: 3.62, majors: ["Economics", "Biology", "Political Science", "Chemistry"] },
  { name: "DePauw University", state: "IN", difficulty_index: 5, gpa_25: 3.15, gpa_50: 3.45, gpa_75: 3.70, majors: ["Economics", "Communication", "Biology", "Political Science"] },
  { name: "Kalamazoo College", state: "MI", difficulty_index: 5, gpa_25: 3.20, gpa_50: 3.48, gpa_75: 3.72, majors: ["Biology", "Business", "Psychology", "Economics"] },
  { name: "Hope College", state: "MI", difficulty_index: 4, gpa_25: 3.10, gpa_50: 3.40, gpa_75: 3.68, majors: ["Engineering", "Business", "Biology", "Education"] },
  { name: "Saint Olaf College", state: "MN", difficulty_index: 5, gpa_25: 3.20, gpa_50: 3.48, gpa_75: 3.72, majors: ["Biology", "Economics", "Mathematics", "Music"] },
  { name: "Lawrence University", state: "WI", difficulty_index: 4, gpa_25: 3.05, gpa_50: 3.35, gpa_75: 3.65, majors: ["Music", "Biology", "Economics", "Government"] },
  { name: "Beloit College", state: "WI", difficulty_index: 4, gpa_25: 2.95, gpa_50: 3.25, gpa_75: 3.58, majors: ["Anthropology", "Biology", "Creative Writing", "Economics"] },
  { name: "Knox College", state: "IL", difficulty_index: 4, gpa_25: 3.00, gpa_50: 3.30, gpa_75: 3.62, majors: ["Creative Writing", "Biology", "Economics", "Education"] },
  { name: "Lake Forest College", state: "IL", difficulty_index: 4, gpa_25: 2.95, gpa_50: 3.25, gpa_75: 3.58, majors: ["Business", "Biology", "Communication", "Psychology"] },
  { name: "Wheaton College (IL)", state: "IL", difficulty_index: 5, gpa_25: 3.25, gpa_50: 3.50, gpa_75: 3.74, majors: ["Business", "Biology", "Psychology", "Music"] },
  { name: "Rose-Hulman Institute of Technology", state: "IN", difficulty_index: 6, gpa_25: 3.50, gpa_50: 3.70, gpa_75: 3.86, majors: ["Engineering", "Computer Science", "Mathematics", "Physics"] },
  { name: "Worcester Polytechnic Institute", state: "MA", difficulty_index: 6, gpa_25: 3.45, gpa_50: 3.65, gpa_75: 3.82, majors: ["Engineering", "Computer Science", "Biology", "Business"] },
  { name: "Rochester Institute of Technology", state: "NY", difficulty_index: 5, gpa_25: 3.30, gpa_50: 3.55, gpa_75: 3.76, majors: ["Engineering", "Computer Science", "Art", "Business"] },
  { name: "Clarkson University", state: "NY", difficulty_index: 4, gpa_25: 3.10, gpa_50: 3.40, gpa_75: 3.68, majors: ["Engineering", "Business", "Computer Science", "Biology"] },
  { name: "University of Puget Sound", state: "WA", difficulty_index: 5, gpa_25: 3.20, gpa_50: 3.48, gpa_75: 3.72, majors: ["Business", "Biology", "Psychology", "Politics"] },
  { name: "Willamette University", state: "OR", difficulty_index: 4, gpa_25: 3.10, gpa_50: 3.40, gpa_75: 3.68, majors: ["Economics", "Biology", "Politics", "Environmental Science"] },
  { name: "University of Richmond", state: "VA", difficulty_index: 6, gpa_25: 3.40, gpa_50: 3.62, gpa_75: 3.80, majors: ["Business", "Biology", "Leadership Studies", "Economics"] },
  { name: "Washington and Lee University", state: "VA", difficulty_index: 7, gpa_25: 3.55, gpa_50: 3.72, gpa_75: 3.86, majors: ["Business", "Economics", "Politics", "Biology"] },
  { name: "University of Scranton", state: "PA", difficulty_index: 4, gpa_25: 3.10, gpa_50: 3.40, gpa_75: 3.68, majors: ["Business", "Biology", "Health Administration", "Nursing"] },
  { name: "Fairfield University", state: "CT", difficulty_index: 5, gpa_25: 3.20, gpa_50: 3.48, gpa_75: 3.72, majors: ["Business", "Nursing", "Biology", "Communication"] },
  { name: "Quinnipiac University", state: "CT", difficulty_index: 4, gpa_25: 3.10, gpa_50: 3.40, gpa_75: 3.68, majors: ["Health Science", "Business", "Communication", "Nursing"] },
  { name: "Sacred Heart University", state: "CT", difficulty_index: 4, gpa_25: 3.05, gpa_50: 3.35, gpa_75: 3.65, majors: ["Business", "Health Science", "Nursing", "Communication"] },
  { name: "Marist College", state: "NY", difficulty_index: 5, gpa_25: 3.20, gpa_50: 3.48, gpa_75: 3.72, majors: ["Business", "Communication", "Psychology", "Computer Science"] },
  { name: "Ithaca College", state: "NY", difficulty_index: 4, gpa_25: 3.05, gpa_50: 3.35, gpa_75: 3.65, majors: ["Communication", "Music", "Business", "Physical Therapy"] },
  { name: "University of Redlands", state: "CA", difficulty_index: 4, gpa_25: 3.00, gpa_50: 3.30, gpa_75: 3.62, majors: ["Business", "Biology", "Music", "Education"] },
  { name: "Saint Mary's College of California", state: "CA", difficulty_index: 4, gpa_25: 3.00, gpa_50: 3.30, gpa_75: 3.62, majors: ["Business", "Biology", "Communication", "Nursing"] },
  { name: "Pacific Lutheran University", state: "WA", difficulty_index: 3, gpa_25: 2.90, gpa_50: 3.20, gpa_75: 3.55, majors: ["Nursing", "Business", "Biology", "Education"] },
  { name: "Seattle University", state: "WA", difficulty_index: 5, gpa_25: 3.25, gpa_50: 3.50, gpa_75: 3.74, majors: ["Business", "Nursing", "Engineering", "Psychology"] },
  { name: "Santa Clara University", state: "CA", difficulty_index: 6, gpa_25: 3.50, gpa_50: 3.70, gpa_75: 3.86, majors: ["Business", "Engineering", "Computer Science", "Communication"] },
];

// Generate unique ID for each college
colleges.forEach((college, index) => {
  college.id = index + 1;
});

// Extract all unique states and majors
export const allStates = [...new Set(colleges.map(c => c.state))].sort();
export const allMajors = [...new Set(colleges.flatMap(c => c.majors))].sort();

export default colleges;